security
gventuri/pandas-ai pull request #54
Opened 2023-05-05 18:01 UTC by VictorGSoutoXP

This PR adds improvements to the LLM-generated code execution code in Python. Added type checking and type conversion capabilities, as well as restricting access to modules and functions deemed unsafe through the use of Python's ast library. In addition, unit tests were performed to ensure the correct functioning of the code. These improvements are expected to increase the security and robustness of code generated by LLM in Python.

2023-05-05 19:37 UTC, gventuri requested changes

2023-05-05 19:37 UTC, gventuri commented on pandasai/llm/security.py
Hey @VictorGSoutoXP could you move this to the helpers folder?
Also, could you also implement this in the LLMs?
Could you also add `matplotlib` to the allowed libraries?
I'm also a little bit concerned of whitelisting only those 3 methods, what do you think?

Finally, as this is a very sensitive change, we should probably enforce it with a few tests, what do you think?

Thanks a lot for the contribution!!

2023-05-06 22:36 UTC, gventuri commented
Hey @VictorGSoutoXP, any updates?

2023-05-08 01:10 UTC, avelino commented
relate PR to issue #43 
People who participated in the discussion in the issue can understand what is being done

2023-05-12 11:52 UTC, gventuri commented
Closing, as the error has been fixed! Thanks @VictorGSoutoXP once again for the support!

2023-05-12 11:52 UTC, closed without merging